### ISSUE TITLE
Open a file, wait a few seconds, then exit directly to the terminal

### ISSUE THREAD

**Issue by doupongzeng** [AstroNvim/template#10]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Operating system/version

ubuntu 20.04

### Terminal/GUI

default

### Describe the bug

Crash without errors, Open a file, wait a few seconds, then exit directly to the terminal

### Steps to Reproduce

rm -rf ~/.local/share/nvim
rm -rf ~/.local/state/nvim
rm -rf ~/.cache/nvim
rm -rf ~/.local/nvim
git clone https://github.com/AstroNvim/template ~/.config/nvim
// Complete initialization
nvim init.lua
// Wait for about 5 seconds, then it will exit back to the terminal

### Expected behavior

work normal

**Comment by mehalter** [comment]
We do not officially support neovim nightly. I would highly recommend using stable neovim for the best AstroNvim experience. If you do try to use experimental and unstable neovim, then you should also disable plugin pinning to allow plugins to update freely. Some plugins have unreleased code that makes them compatible for Neovim nightly.
