### ISSUE TITLE
new mappings for L and H hide built-in vim mappings

### ISSUE THREAD

**Issue by dpriedel** [AstroNvim/template#13]
### Checklist

- [X] I have searched through the AstroNvim docs
- [X] I have searched through the existing issues of AstroNvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Manjaro Linux

### Terminal/GUI

wezterm

### Describe the bug

The new 'simplified' key mappinigs for 'L' and 'H'  to switch buffers hide the built-in vim mappings for moving up and down in the screen.
Since we already have ']b' and '[b' to move between buffers, these additional mappings provide no new function and remove old useful function.

### Steps to Reproduce

1. open a file
2. open a second file
3. type 'L'.  Instead of moving to the bottom of the visible area of the buffer, the display swithes the other buffer

### Expected behavior

I expect 'L' and 'H' to move to bottom and top of the content displayed in the screen.

### Additional Context

These mappings have been added and then removed before.

**Comment by mehalter** [comment]
These are just examples and this reason is exactly why those mappings are not in AstroNvim. We provide those examples purely because that's the most requested mappings. These example files are disabled by default as to not provide them unless the user wants them

**Comment by dpriedel** [comment]
Thanks for your response.


But, if you have the file enabled and you pick up an update, then you 
get these key mappings.


I think it would be better if they were commented out. That way, you 
could still provide the example

but they wouldn't interfere with anyone's setup.


Thanks

**Comment by mehalter** [comment]
Ah yeah no need to pull updates once you use the template! It's just a good starting point. No need to be bound to what's in this repo or the structure it provides. It is not expected or recommended to continuously update based on this repo once you do your own configuration. Updates for actual AstroNvim are delivered through Lazy.
