### ISSUE TITLE
windows Installation very wrong instructions

### ISSUE THREAD

**Issue by LeonardoDaLuz** [AstroNvim/template#18]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.95

### Operating system/version

windows 11

### Terminal/GUI

Windows Terminal

### Describe the bug

`$env:LOCALAPPDATA\nvim` doesnt exists.
`git clone --depth 1 https://github.com/AstroNvim/template $env:LOCALAPPDATA\nvim`
There is no neovim .exe executable in this folder. Then it won't work.
![image](https://github.com/neovim/neovim/assets/80224694/4230e042-a6d5-4eea-843b-956d2fa8c50d)

### Steps to Reproduce

follow astrovim windows instalation instruction.

### Expected behavior

.exe in folder.

### Additional Context

My neovim was installed using winget. I Tried instaling .msi also.

### Minimal configuration

```Lua
default
```

**Comment by mehalter** [comment]
Reading through this again and it doesn't appear that the instructions are incorrect. The installation of AstroNvim should not provide any `.exe` file in any folder.

These are the same instructions that neovim recommends and all of the other popular distributions use. I don't personally use windows so I can't help out too much. Check out the Discord server if you want to ask some more questions to other users who probably have experience that can help you.

**Comment by LeonardoDaLuz** [comment]
Yes, there is no .exe in that folder because the tutorial tells you to move it to the nvim.bak folder.
I tried simply throwing the template folder into the nvim folder, I tried throwing it into the root folder but it didn't work. I gave up. It could just be like every Windows program where there is an .exe installer that solves everything.

**Comment by mehalter** [comment]
Yeah this is definitely coming from a misunderstanding along the way. You shouldn't be installing the `nvim.exe` file into your `$env:LOCALAPPDATA\nvim`. If you don't have a previous neovim configuration then that folder will not exist. That is the folder that neovim will _look_ for a configuration. If you don't have one then it will just be stock. I just did a fresh windows 10 installation and followed the installation instructions for neovim and AstroNvim from the documentation and it worked perfectly fine.

**Comment by mehalter** [comment]
It might help to read a bit on how neovim configuration works in general specifically with Windows and how to make  a neovim configuration

**Comment by LeonardoDaLuz** [comment]
It finally worked, the thing is that you simply have to ignore the error in the first command, and continue with the others.
![image](https://github.com/AstroNvim/template/assets/80224694/2e57ea56-0412-46c6-95b7-6662eec55234)

**Comment by mehalter** [comment]
Yeah, if you have a neovim configuration previously then it will not error.

**Comment by LeonardoDaLuz** [comment]
thank you so much!
There could be a hint about this in the tutorial.

**Comment by mehalter** [comment]
Sure, I added an "if exists" text to the instruction: https://docs.astronvim.com/#-installation
