### ISSUE TITLE
Add a border around Lazy UI window

### ISSUE THREAD

**Issue by jondkinney** [AstroNvim/template#21]
### Is your feature related to a problem?

A visual display consistency problem, yes. 

Some color schemes have the exact same background color for the lazy UI interface pop up window as the main background. When that is the case (nord, for example) when the Lazy UI is open the overall screen looks kind of broken. I'd suggest making the change described below to add a border to the Lazy window.

### Describe the new feature

Update this line https://github.com/AstroNvim/template/blob/20450d8a65a74be39d2c92bc8689b1acccf2cffe/lua/lazy_setup.lua#L19

To be 
```lua
  ui = { backdrop = 100, border = "single" },
```

### Additional context

Without Lazy Open
![CleanShot 2024-07-23 at 23 26 15@2x](https://github.com/user-attachments/assets/523659de-dd0c-473d-baba-459af58548b3)

With Lazy open with default settings (blends into surrounding buffers/text oddly)
![CleanShot 2024-07-23 at 23 29 22@2x](https://github.com/user-attachments/assets/3494bb10-0ea7-4455-bc7a-679e25429e8c)

With Lazy open with `border="single"`
![CleanShot 2024-07-23 at 23 27 43@2x](https://github.com/user-attachments/assets/2ef12232-2cb5-42ec-8ce0-78f10aa95ee4)

My personal preference, both `border="single"` and `backdrop = 90`
![CleanShot 2024-07-23 at 23 28 37@2x](https://github.com/user-attachments/assets/1b95369f-9ed1-43a5-b30e-8231e698f24f)

**Comment by mehalter** [comment]
Thanks for the recommendation! The code here is really just a starting point for users and so the goal is to be as simple as possible. This repo is really  just a starting point for customization with no one tracking ongoing changes here. As the user makes changes like a custom colorscheme, they may want to customize how things look which is totally up to them, so I don't think this is a change we want to make here, but feel free to make the change in your own configuration. Also this would make some discontinuity out of the box between the Mason UI and Lazy.
