### ISSUE TITLE
This is really confusing

### ISSUE THREAD

**Issue by thepragmaticmero** [AstroNvim/template#23]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

0.10.1

### Operating system/version

Fedora Silverblue 40

### Terminal/GUI

alacritty

### Describe the bug

Writing "vim.opt.wrap = true" on \~/.config/nvim/init.lua , below all the other text. Does NOT change my wrapping. Also why is wrapping disabled by default? and "\~/.config/nvim/init.lua" not the init.lua config? I'd read some parts of the documentation and haven't found anything on where or what file should I edit to use a custom config.

### Steps to Reproduce

I just write "set wrap" using `:` every time I enter AstroNvim

### Expected behavior

duh

### Additional Context

Just frustration that's all. I'm gonna go minimal plugins anyways.

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by thepragmaticmero** [comment]
fixed writing `vim.opt.wrap=true` on `/home/user/config/nvim/lua/lazy_setup.lua`. Writing it on a setup file huh..... time to rethink i guess.

**Comment by mehalter** [comment]
You can change vim options in the AstroCore plugin configuration as shown in the template:

https://github.com/AstroNvim/template/blob/main/lua%2Fplugins%2Fastrocore.lua#L27-L35

**Comment by thepragmaticmero** [comment]
mmm so that's the correct way then. Ok~ tnks.
