### ISSUE TITLE
Error executing vim.schedule lua callback

### ISSUE THREAD

**Issue by vanxxxx** [AstroNvim/template#26]
### Checklist

- [X] I have searched through the AstroNvim documentation
- [X] I have searched through the existing issues of this project
- [X] I have searched the existing issues of plugins related to this issue
- [X] I can replicate the bug with the minimal `repro.lua` provided below

### Neovim version (nvim -v)

v0.11.0-dev-1210+g3597633075

### Operating system/version

Windows11 with wsl 2 

### Terminal/GUI

Windows Terminal

### Describe the bug

I follow start guide install astronvim but whenever i enter an .py file,

vim.lsp.get_active_clients() is deprecated. Run ":checkhealth vim.deprecated" for more information
Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
...share/nvim/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:177: attempt to call method 'range' (a nil value)

will show in bottom

and when i change insert mode to normal mode by esc,

Error executing vim.schedule lua callback: UnhandledPromiseRejection with the reason:
...share/nvim/lazy/nvim-ufo/lua/ufo/provider/treesitter.lua:177: attempt to call method 'range' (a nil value)
Press ENTER or type command to continue  

will show in bottom
What should i do to fix it

### Steps to Reproduce

open a py file

### Expected behavior

N

### Screenshots

![image](https://github.com/user-attachments/assets/bf047006-baef-4836-bcc2-ad7c263faef0)
![image](https://github.com/user-attachments/assets/6272b089-a841-4868-9cc6-bfd25f244877)
![image](https://github.com/user-attachments/assets/5c79d50d-e2bb-40ed-9a1f-b69d9cbe20bc)

### Minimal configuration

```Lua
-- save as repro.lua
-- run with nvim -u repro.lua
-- DO NOT change the paths
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "runtime", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)

-- install plugins
local plugins = {
  { "AstroNvim/AstroNvim", import = "astronvim.plugins" },
  { "AstroNvim/astrocommunity" },

  -- add any other plugins/customizations here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here (autocommands, vim.filetype, etc.)
```

**Comment by vanxxxx** [comment]
I also follow to run :checkhealth deprecated
[checkhealth.txt](https://github.com/user-attachments/files/17945812/checkhealth.txt)

**Comment by mehalter** [comment]
Thanks for reporting, looks like nvim-ufo doesn't support 0.11 yet which makes sense. That is an unsupported version because of stuff like this. I'll go ahead and close this since nothing is actionable on the AstroNvim side.
